import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { ChartBar, Users, Handshake, Activity } from 'lucide-react';
export default function Dashboard() {
    return (_jsxs("div", { className: "space-y-6", children: [_jsxs("div", { className: "grid sm:grid-cols-2 lg:grid-cols-4 gap-4", children: [_jsx(StatCard, { title: "Active Deals", value: "34", icon: _jsx(Handshake, { className: "text-brand-600" }), trend: "+3.2%" }), _jsx(StatCard, { title: "New Contacts", value: "186", icon: _jsx(Users, { className: "text-brand-600" }), trend: "+1.1%" }), _jsx(StatCard, { title: "Win Rate", value: "27%", icon: _jsx(ChartBar, { className: "text-brand-600" }), trend: "+0.4%" }), _jsx(StatCard, { title: "Activities", value: "71", icon: _jsx(Activity, { className: "text-brand-600" }), trend: "-0.8%" })] }), _jsxs("div", { className: "grid lg:grid-cols-3 gap-4", children: [_jsxs("div", { className: "card p-4 lg:col-span-2", children: [_jsx("h3", { className: "font-semibold mb-3", children: "Pipeline Snapshot" }), _jsx("div", { className: "overflow-auto", children: _jsxs("table", { className: "min-w-full text-sm", children: [_jsx("thead", { className: "text-left text-slate-500", children: _jsxs("tr", { children: [_jsx("th", { className: "py-2 pr-4", children: "Deal" }), _jsx("th", { className: "py-2 pr-4", children: "Stage" }), _jsx("th", { className: "py-2 pr-4", children: "Owner" }), _jsx("th", { className: "py-2 pr-4 text-right", children: "Value" })] }) }), _jsx("tbody", { children: ['Acme Onboarding', 'Globex Renewal', 'Umbrella Pilot', 'Soylent Upgrade'].map((d, i) => (_jsxs("tr", { className: "border-t border-slate-100 dark:border-slate-800", children: [_jsx("td", { className: "py-2 pr-4", children: d }), _jsx("td", { className: "py-2 pr-4", children: _jsx("span", { className: "badge badge-amber", children: "In Progress" }) }), _jsx("td", { className: "py-2 pr-4", children: "A. Khan" }), _jsxs("td", { className: "py-2 pl-4 text-right", children: ["PKR ", (100000 + i * 25000).toLocaleString()] })] }, i))) })] }) })] }), _jsxs("div", { className: "card p-4", children: [_jsx("h3", { className: "font-semibold mb-3", children: "Recent Activity" }), _jsx("ul", { className: "text-sm space-y-3", children: ['Call scheduled with Globex', 'Proposal sent to Umbrella', 'Deal moved to Qualified', 'New contact added: S. Ahmed'].map((a, i) => (_jsxs("li", { className: "flex items-center gap-2", children: [_jsx("span", { className: "h-2 w-2 rounded-full bg-brand-500" }), _jsx("span", { children: a })] }, i))) })] })] })] }));
}
function StatCard({ title, value, icon, trend }) {
    const good = trend.startsWith('+');
    return (_jsxs("div", { className: "card p-4 flex items-center justify-between", children: [_jsxs("div", { children: [_jsx("div", { className: "text-slate-500 dark:text-slate-400 text-sm", children: title }), _jsx("div", { className: "text-2xl font-semibold", children: value }), _jsxs("div", { className: `${good ? 'text-green-600' : 'text-rose-600'} text-xs`, children: [trend, " vs last week"] })] }), _jsx("div", { className: "h-12 w-12 rounded-xl bg-brand-50 dark:bg-slate-900 flex items-center justify-center", children: icon })] }));
}
